const router = require('koa-router')
const Project = require('../controllers/project')
const Picture = require('../controllers/picture')
const User = require('../controllers/user')
exports.api = router({prefix: '/api'})
  .get('/project/list', Project.list)
  .get('/project/:projectId', Project.detail)
  .post('/project/:projectId', Project.create)
  .get('/project/:projectId/:itemId', Project.show)
  .put('/project/:projectId/:itemId', Project.update)
  .post('/login', User.login)
  .get('/picture', Picture.list)
  .get('/picture/:bucketId', Picture.detail)
  .get('/picture/:bucketId/token', Picture.token)
  .post('/picture/:bucketId', Picture.create)

exports.cloud = router({prefix: '/cloud'})
  .get('/:projectId/:path*', Project.content)
