const router = require('koa-router')
const Project = require('../controllers/project')
exports.api = router({prefix: '/api'})
  .get('/project/list', Project.list)
  .get('/project/:projectId', Project.detail)
  .post('/project/:projectId', Project.create)
  .get('/project/:projectId/:itemId', Project.show)
  .put('/project/:projectId/:itemId', Project.update)

exports.cloud = router({prefix: '/cloud'})
  .get('/:projectId/:path*',Project.content)
